name: benjamin.paris
favicon: null
layout_spectrum: 0.4962510538753122
typography_spectrum: 0.5944718248210847
title: 'Benjamin - Craft & More'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.3794804085046053
  lightness: 0.02253139903768897
  saturation: 0.1755767036229372
  rhythmicContrast: 0.4905137266032398
purpose: []
